/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PatientScreen_AllPatientsQuery.graphql
 * @generated SignedSource<<db9bc2b246189818c09dfc17fd23e117>>
 * @relayHash 823040f3b93bc086e8f06d7847744754
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query PatientScreen_AllPatientsQuery {
  query {
    ...PatientList_query
    id
  }
}

fragment PatientList_query on Query {
  ...Patient_query
  allPatients(first: 5, orderBy: NAME_ASC) {
    edges {
      node {
        ...Patient_patient
        id
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}

fragment Patient_query on Query {
  id
}

fragment Patient_patient on Patient {
  id
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "PatientScreen_AllPatientsQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Query",
        "name": "query",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "PatientList_query",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "PatientScreen_AllPatientsQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "PatientScreen_AllPatientsQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Query",
        "name": "query",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "InlineFragment",
            "type": "Query",
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": [
                  {
                    "kind": "Literal",
                    "name": "first",
                    "value": 5,
                    "type": "Int"
                  },
                  {
                    "kind": "Literal",
                    "name": "orderBy",
                    "value": "NAME_ASC",
                    "type": "PatientsOrderBy"
                  }
                ],
                "concreteType": "PatientsConnection",
                "name": "allPatients",
                "plural": false,
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": null,
                    "concreteType": "PatientsEdge",
                    "name": "edges",
                    "plural": true,
                    "selections": [
                      {
                        "kind": "LinkedField",
                        "alias": null,
                        "args": null,
                        "concreteType": "Patient",
                        "name": "node",
                        "plural": false,
                        "selections": [
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "id",
                            "storageKey": null
                          },
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "__typename",
                            "storageKey": null
                          }
                        ],
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "cursor",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  },
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": null,
                    "concreteType": "PageInfo",
                    "name": "pageInfo",
                    "plural": false,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "endCursor",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "hasNextPage",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "hasPreviousPage",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "startCursor",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  }
                ],
                "storageKey": "allPatients{\"first\":5,\"orderBy\":\"NAME_ASC\"}"
              },
              {
                "kind": "LinkedHandle",
                "alias": null,
                "args": [
                  {
                    "kind": "Literal",
                    "name": "first",
                    "value": 5,
                    "type": "Int"
                  },
                  {
                    "kind": "Literal",
                    "name": "orderBy",
                    "value": "NAME_ASC",
                    "type": "PatientsOrderBy"
                  }
                ],
                "handle": "connection",
                "name": "allPatients",
                "key": "PatientList_allPatients",
                "filters": []
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query PatientScreen_AllPatientsQuery {\n  query {\n    ...PatientList_query\n    id\n  }\n}\n\nfragment PatientList_query on Query {\n  ...Patient_query\n  allPatients(first: 5, orderBy: NAME_ASC) {\n    edges {\n      node {\n        ...Patient_patient\n        id\n        __typename\n      }\n      cursor\n    }\n    pageInfo {\n      endCursor\n      hasNextPage\n      hasPreviousPage\n      startCursor\n    }\n  }\n}\n\nfragment Patient_query on Query {\n  id\n}\n\nfragment Patient_patient on Patient {\n  id\n}\n"
};

module.exports = batch;
