/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PatientList_query.graphql
 * @generated SignedSource<<6c6888a249f78925669386cf9252bfa6>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PatientList_query = {|
  +allPatients: ?{|
    +edges: ?$ReadOnlyArray<?{|
      +node: {| |};
    |}>;
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": null,
        "cursor": null,
        "direction": "forward",
        "path": [
          "allPatients"
        ]
      }
    ]
  },
  "name": "PatientList_query",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "Patient_query",
      "args": null
    },
    {
      "kind": "LinkedField",
      "alias": "allPatients",
      "args": null,
      "concreteType": "PatientsConnection",
      "name": "__PatientList_allPatients_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "PatientsEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Patient",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "FragmentSpread",
                  "name": "Patient_patient",
                  "args": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Query"
};

module.exports = fragment;
