/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Patient_patient.graphql
 * @generated SignedSource<<340cd5502f405f6e543e86a9a2932d1a>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Patient_patient = {|
  +id: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Patient_patient",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    }
  ],
  "type": "Patient"
};

module.exports = fragment;
