/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Patient_query.graphql
 * @generated SignedSource<<35a09d3edb3acbbbb5cb773bc2ed0b39>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Patient_query = {|
  +id: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Patient_query",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    }
  ],
  "type": "Query"
};

module.exports = fragment;
